### ISSUE TITLE
Broken reading of a Save of The Sacred Tears TRUE

### ISSUE THREAD

**Issue by Zegeri** [EasyRPG/liblcf#155]
This save file shared by @carstene1ns for EasyRPG/Player#579 is incorrectly parsed:
http://f4ke.de/dev/easyrpg/TSTT/Save03.lsd

When run with _DEBUG, it'll warn about multiple skipped chunks and it'll crash because of running out of bytes. What breaks liblcf is a keyinput_variable (0x16) at 0x3846, inside the SaveEventData of the 8th CommonEvent.

```
16 01 8C 17 01 01
```
should be parsed as:
```
keyinput_variable (size 01) (value 8c)
keyinput_all_directions (size 01) (value 01)
```

But it's actually parsed as:
```
keyinput_variable (size 01) (value 8c 17)
[crap]
```

keyinput_variable saves the variable used by the last KeyInputProc. Here's the funny part. In this case, the last KeyInputProc saves the input value in the variable 908. Now: 908 = 0x03**8C**. So keyinput_variable seems to be actually saving the last byte, not the whole number.

**Comment by Ghabry** [comment]
I can't even get the KeyInput in a simple test case to work.

Have an Auto Start Common Event that reads Left/Right and then Waits 1.0 second and a map event that changes its look based on the button. The look never changes :(

**Comment by Zegeri** [comment]
That setup you've described works on my end. Try running it in TestPlay mode and looking at the table of variables during that second.

**Comment by Ghabry** [comment]
Yeah the problem I encountered was a different bug

**Comment by CherryDT** [comment]
This is a bug I knew about for a long time but not the cause. Turns RM incorrectly saves this variable as boolean (which internally just copies 1 byte) instead of a var-len integer, probably a copy-paste error from the surrounding booleans.

Unfortunately this means it's hard to fix for me because if I would simply change this into an integer, then RPG_RT would encounter the same problem you had for certain saves and crash with a "stream read error" for bytes with the highest bit set. I'll see, maybe I'll save in a new chunk and load from both so that compatibility (at least for variables <128) is still okay.
