### ISSUE TITLE
2000 and 2003 picture command transparency data is different

### ISSUE THREAD

**Issue by ghost** [EasyRPG/liblcf#22]
Look at the transparency block:
2000 1.52:
![](http://img94.imageshack.us/img94/9172/qttempem7372.png)
2003 1.09a:
![](http://img338.imageshack.us/img338/3125/qttemphp7372.png)

2000 has **1 picture transparency value**
2003 has **2 picture transparency values**: top half and bottom half

Picture commands saved with RPG Maker 2000 are showing only top half of the image:
![](http://img822.imageshack.us/img822/1869/19109385.png)

Binary diff between 2000 saved LMU and 2003 saved LMU:
![](http://img6.imagebanana.com/img/vsox9vsq/mapdiff.png)

Possible reason:
- Readers or Player could expect 2 transparency values, and missing 2nd value is being interpreted as used in game in the wrong way as 100% transparent by default (transparency vs opacity misinterpretation?), instead of processing 2 halves for games without this data chunk.

Possible solution:
- Fix Readers or Player to handle 2000 picture opacity data chunk properly according with actual data contents.

**Comment by CherryDT** [comment]
> transparency vs opacity misinterpretation?
No, they were just sloppy, it would appear. (Something you note at many things which were added in RM2k3 by different people than the RM2k author.) That's also the reason for the extra event command parameter by the way: After the parameter [14] which is the second-half trasparency, there is a parameter [15] which contains junk because they sized the list of parameters too high by one and then didn't use it, so the last parameter contains uninitialized random memory garbage.

(Btw I never understood what that two-half thing was even supposed to be good for. That's why I removed it in v1.10.)

**Comment by fdelapena** [comment]
Yeah, I fixed this in EasyRPG/Player#185 and Zegeri fixed the behavior change since 2k3 1.10 reported in issue EasyRPG/Player#539

**Comment by Ghabry** [comment]
Yepp this feature feels completely useless, if it would be a transparency gradient there would be at least a slight usage... but in the 2003 way it is nonsense.

2k3 feels strange in many situations. The ways classes are handled, makes no sense either. Why can you assign an actor a class in the database but it will not take the attributes of the class until you call "Change Class" once...
